export const actualData = {
  iati_identifier: "FR-3-CBR1090",
  reporting_org_ref: "FR-3",
  reporting_org_narrative: "Agence Française de Développement",
  reporting_org_type: "",
  title:
    "Appui à la transformation de la stratégie de financement de la BRDE en faveur des Objectifs de Développement Durable ",
  dates: ["2021-01-12", ""],
  description:
    "En appuyant la BRDE dans la mise en place d'une stratégie « développement durable » et en renforçant ses capacités financières et opérationnelles, ce projet a pour objectif d'accompagner la banque dans son évolution stratégique afin de lui permettre de mieux remplir son mandat d'institution publique de développement et son ambition de s'affirmer comme pionnière dans la promotion de l'Agenda 2030. ",
  budgets: [
    {
      type: "Original",
      status: "Indicative",
      start: "2023-07-12",
      end: "2023-08-11",
      value: "€2,258,064.50",
    },
    {
      type: "Original",
      status: "Indicative",
      start: "2023-04-12",
      end: "2023-07-11",
      value: "€6,774,193.55",
    },
    {
      type: "Original",
      status: "Indicative",
      start: "2023-01-12",
      end: "2023-04-11",
      value: "€6,774,193.55",
    },
    {
      type: "Original",
      status: "Indicative",
      start: "2022-10-12",
      end: "2023-01-11",
      value: "€6,774,193.55",
    },
    {
      type: "Original",
      status: "Indicative",
      start: "2022-07-12",
      end: "2022-10-11",
      value: "€6,774,193.55",
    },
    {
      type: "Original",
      status: "Indicative",
      start: "2022-04-12",
      end: "2022-07-11",
      value: "€6,774,193.55",
    },
    {
      type: "Original",
      status: "Indicative",
      start: "2022-01-12",
      end: "2022-04-11",
      value: "€6,774,193.55",
    },
    {
      type: "Original",
      status: "Indicative",
      start: "2021-10-12",
      end: "2022-01-11",
      value: "€6,774,193.55",
    },
    {
      type: "Original",
      status: "Indicative",
      start: "2021-07-12",
      end: "2021-10-11",
      value: "€6,774,193.55",
    },
    {
      type: "Original",
      status: "Indicative",
      start: "2021-04-12",
      end: "2021-07-11",
      value: "€6,774,193.55",
    },
    {
      type: "Original",
      status: "Indicative",
      start: "2021-01-12",
      end: "2021-04-11",
      value: "€6,774,193.55",
    },
  ],
  participating_orgs: [
    {
      name: "France",
      reference: "FR",
      type: "Government",
      role: "Funding",
      url: "/organisation/FR/projects",
    },
  ],
  summary: {
    status: "Implementation",
    scope: "no data",
    collaboration_type: "no data",
    default_flow_type: "no data",
    default_finance_type: "no data",
    default_tied_status: "no data",
    capital_spend: "no data",
    planned_start: "2021-01-12",
    actual_start: "2021-01-12",
    planned_end: "2023-08-11",
    actual_end: "no data",
  },
  countries: [
    {
      name: "Brazil",
      code: "BR",
      percentage: "no data",
      url: "/country/Brazil/projects",
    },
  ],
  regions: [],
  locations: [],
  humanitarian_scopes: [],
  sectors: [
    {
      name: "Vocabulary 99 or 98",
      code: "7",
      percentage: "no data",
      url: "/publisher/FR-3/sectors?sector_code=7",
    },
    {
      name: "Sectors not specified",
      code: "99810",
      percentage: "no data",
      url: "/publisher/FR-3/sectors?sector_code=99810",
    },
  ],
  default_aid_types: [],
  policy_markers: [],
  tags: [],
  contact_info: {
    type: "no data",
    telephone: "no data",
    email: "no data",
    website: "no data",
    organisation: "no data",
    department: "no data",
    person: "no data",
    position: "no data",
    mailing_address: "no data",
  },
  other_identifiers: [],
  country_budget_items: [],
  planned_disbursements: [],
  document_links: [],
  related_activities: [
    { ref: "FR-3-CBR109001", type: "2", url: "/project/FR-3-CBR109001" },
  ],
  legacy_data: [],
  conditions: [],
};
