export const lists = [
  {
    id: "budget",
    label: "Budget",
    description: "budget desc",
    path: "budget",
    dataPath: "budgets",
    dataType: "array",
    expanded: false,
  },
  {
    id: "participating_orgs",
    label: "Participating organisations",
    description: "participating_orgs desc",
    path: "participating_orgs",
    dataPath: "participating_orgs",
    dataType: "array",
    expanded: false,
  },
  {
    id: "activity_summary",
    label: "Activity summary",
    description: "activity_summary desc",
    path: "activity_summary",
    dataPath: "summary",
    dataType: "object",
    expanded: false,
  },
  {
    id: "recipient_countries",
    label: "Recipient countries",
    description: "recipient_countries desc",
    path: "recipient_countries",
    dataPath: "countries",
    dataType: "array",
    expanded: false,
  },
  {
    id: "recipient_regions",
    label: "Recipient regions",
    description: "recipient_regions desc",
    path: "recipient_regions",
    dataPath: "regions",
    dataType: "array",
    expanded: false,
  },
  {
    id: "locations",
    label: "Locations",
    description: "locations desc",
    path: "locations",
    dataPath: "locations",
    dataType: "array",
    expanded: false,
  },
  {
    id: "humanitarian_scope",
    label: "Humanitarian scope",
    description: "humanitarian_scope desc",
    path: "humanitarian_scope",
    dataPath: "humanitarian_scope",
    dataType: "array",
    expanded: false,
  },
  {
    id: "sectors",
    label: "Sectors",
    description: "sectors desc",
    path: "sectors",
    dataPath: "sectors",
    dataType: "array",
    expanded: false,
  },
  {
    id: "default_aid_type",
    label: "Default aid type",
    description: "default_aid_type desc",
    path: "default_aid_type",
    dataPath: "default_aid_types",
    dataType: "array",
    expanded: false,
  },
  {
    id: "policy_marker",
    label: "Policy marker",
    description: "policy_marker desc",
    path: "policy_marker",
    dataPath: "policy_markers",
    dataType: "array",
    expanded: false,
  },
  {
    id: "tags",
    label: "Tags",
    description: "tag desc",
    path: "tags",
    dataPath: "tags",
    dataType: "array",
    expanded: false,
  },
  {
    id: "contact_information",
    label: "Contact information",
    description: "contact_information desc",
    path: "contact_information",
    dataPath: "contact_info",
    dataType: "object",
    expanded: false,
  },
  {
    id: "other_identifiers",
    label: "Other identifiers",
    description: "other_identifiers desc",
    path: "other_identifiers",
    dataPath: "other_identifiers",
    dataType: "array",
    expanded: false,
  },
  {
    id: "country_budget_items",
    label: "Country budget items",
    description: "country_budget_items desc",
    path: "country_budget_items",
    dataPath: "country_budget_items",
    dataType: "array",
    expanded: false,
  },
  {
    id: "planned_disbursements",
    label: "Planned disbursements",
    description: "planned_disbursements desc",
    path: "planned_disbursements",
    dataPath: "planned_disbursements",
    dataType: "array",
    expanded: false,
  },
  {
    id: "document_links",
    label: "Document links",
    description: "document_links desc",
    path: "document_links",
    dataPath: "document_links",
    dataType: "array",
    expanded: false,
  },
  {
    id: "related_activities",
    label: "Related activities",
    description: "related_activities desc",
    path: "related_activities",
    dataPath: "related_activities",
    dataType: "array",
    expanded: false,
  },
  {
    id: "legacy_data",
    label: "Legacy data",
    description: "legacy_data desc",
    path: "legacy_data",
    dataPath: "legacy_data",
    dataType: "array",
    expanded: false,
  },
  {
    id: "conditions",
    label: "Conditions - not attached",
    description: "conditions desc",
    path: "conditions",
    dataPath: "conditions",
    dataType: "array",
    expanded: false,
  },
];
